### ISSUE TITLE
Documentation: Arch Linux commands to install dependencies

### ISSUE THREAD

**Issue by lordadamson** [lordadamson/Journal#101]
In the readme.md we have instructions to install dev environment on fedora and ubuntu.
If you have Arch Linux could you tell us what are the proper commands?

**Comment by chicao** [comment]
I compiled and built Journal at Archlinux. If you are ok, I can write a more detailed documentation on what I did to compile it properly.

**Comment by lordadamson** [comment]
Yes please do and pull request. I'd happily accept it.

On Sep 29, 2017 4:00 PM, Francisco Fernandes <notifications@github.com> wrote:

I compiled and built Journal at Archlinux. If you are ok, I can write a more detailed documentation on what I did to compile it properly.

**Comment by chicao** [comment]
Cool. I'll add it ASAP. :)
