### ISSUE TITLE
Journal fails to build

### ISSUE THREAD

**Issue by dubielt1** [lordadamson/Journal#105]
Master branch
Latest commit 9d1a637
OS: Fedora 26

I installed qt-5 as mentioned in the ReadMe. I imported the project file into qt Creator, and the configuration is identical to the example image in the ReadMe (except my username in the paths, of course).

2 Errors:

{path}/Journal/huge_dictionary.h:1: error: ‘version’ does not name a type; did you mean ‘qVersion’?
{path}/Journal/paper.cpp:180: error: ‘huge_dictionary’ was not declared in this scope
     QString newName = QString::fromStdString(huge_dictionary[index] + " ");
                                              ^~~~~~~~~~~~~~~

I was going to see if I could jump in and contribute to your project, look forward to your reply.

**Comment by lordadamson** [comment]
Hi there buddy. Sounds like you don't have git lfs installed.
Install it and reclone and let me know.

On Oct 3, 2017 2:42 AM, Tres DuBiel <notifications@github.com> wrote:

Master branch
Latest commit 9d1a637<https://github.com/lordadamson/Journal/commit/9d1a6373cdafc776074f1a9807712e018c33c07d>
OS: Fedora 26

I installed qt-5 as mentioned in the ReadMe. I imported the project file into qt Creator, and the configuration is identical to the example image in the ReadMe (except my username in the paths, of course).

2 Errors:

{path}/Journal/huge_dictionary.h:1: error: ‘version’ does not name a type; did you mean ‘qVersion’?
{path}/Journal/paper.cpp:180: error: ‘huge_dictionary’ was not declared in this scope
QString newName = QString::fromStdString(huge_dictionary[index] + " ");
^~~~~~~~~~~~~~~

I was going to see if I could jump in and contribute to your project, look forward to your reply.

**Comment by dubielt1** [comment]
That did the trick!
