### ISSUE TITLE
it would be better if there were a list for the modes

### ISSUE THREAD

**Issue by Ahmed-Ayman** [lordadamson/Journal#77]
I got confused when I opened it..
it would be better if you can do a list when I Right-Click to show me the different modes
another thing , there is no an option for deleting the stuff
.....
hopefully I could contribute with you soon , just started learning about Qt , 
the project is awesome by the way!

**Comment by lordadamson** [comment]
Hi :D I don't understand what modes mean. Care to explain?
deleting stuff is in progress: issue #66 
Would love to see pull requests from you soon, and thank you :D

**Comment by Ahmed-Ayman** [comment]
I just meant the  <Select , Draw , ... > options 😄 
just meant something like that one in the center.

![JOURNAL](http://i.imgur.com/u7dlFD3.png)

**Comment by lordadamson** [comment]
okay so you think it's a good idea to have a context menu having all the tools like select and draw. Well from a usability point of view I don't think that's what most users would expect. Context menus usually contain options regarding the currently selected item. so it can for example have delete, cut and copy.

What's wrong with having the tools in the toolbar at the top?
